services:
  producer:
    build:
      target: dev
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules

  consumer:
    build:
      target: dev
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules

  telegram-service:
    build:
      target: dev
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules

  api-gateway:
    build:
      target: dev
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
